### PR TITLE
Always fetch intervention data on details and edit screens

### PR DESCRIPTION
**Pull request by chodorowicz**
Solves: https://github.com/lightning-team/Ekostraz/issues/83

### CODE REVIEW

**Comment by chodorowicz** [comment]
Too easy? 😄

**Comment by CorneeSean** [comment]
Yep, that's not enough ;) There is also router redirect with passed state that needs to be cleaned up, as we are not using this state anymore :) Search for the `InterventionRouterState` type definition to find it.

**Comment by chodorowicz** [comment]
@CorneeSean OK, done, I've removed `InterventionRouterState`

**Comment by CorneeSean** [comment]
Works good, merging!

**Pull request merged**
