### PR TITLE
feat(frontend/scrollbar): Style scrollbar

### PR DESCRIPTION
**Pull request by CorneeSean**
Nothing fancy - just making it look better than the default.

style_scrollbar

### CODE REVIEW

**Comment by chodorowicz** [comment]
It might look better on Windows, but on macOS it looks non standard and and a bit worse tbh. In webkit on macOS scrollbar is disappearing when when there's not scrolling and it's also overflowing the content.
If you really want to change the default then here's something that mimics better  this behavior.
https://jsfiddle.net/7knd1gLz/1/

**Comment by chodorowicz** [comment]
https://www.dropbox.com/s/8l72j5zig9emxdm/macos-scrollbar.mp4?dl=0

**Comment by CorneeSean** [comment]
I hoped this would be a quick fix so let's leave it for now, unless you want to finish it instead :)

**Comment by CorneeSean** [comment]
Not relevant

**Pull request closed without merging**
